<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Billboard;
use Illuminate\Support\Str;

class BillboardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $billboards = [
            [
                'code' => 'BB-02',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. GATOT SUBROTO SIMP. BARAT',
                'size' => '6 m x 12 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/LU83uSuSsRKW3nZH9',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 14 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Traffic Padat\nMenuju Manhattan Mall\nMenuju Pajak Sei Kambing\nMenuju Brastagi Supermarket Gatot Subrot\nPadat Pemukiman\nDekat Perkantoran & Pertokoan\nDekat Cafe & Restoran',
                'traffic_weekly_motor' => 1179877,
                'traffic_weekly_mobil' => 1056345,
                'traffic_weekly_bus' => 5743,
                'traffic_weekly_truk' => 16492,
                'traffic_monthly_motor' => 5778492,
                'traffic_monthly_mobil' => 4958723,
                'traffic_monthly_bus' => 26431,
                'traffic_monthly_truk' => 76198,
            ],
            [
                'code' => 'BB-03',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. GURU PATIMPUS SIMP JL. MANGGIS',
                'size' => '16 m x 8 m',
                'orientation' => 'Horizontal',
                'maps_link' => 'https://maps.app.goo.gl/3Nv8PHzYBzYaWjY6',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 24 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => '± 350m dari Mall Deli Pomodoro\n± 500m dari Hotel JW Marriot\nMenuju Plaza Medan Fair\nDekat Showroom Mobil\nDekat Toko-Toko Elektronik\nDekat Kantor DPRD Sumut dan Kota Medan\nMenuju Kantor Walikota\nMenuju Lapangan Benteng\nMenuju Lapangan Merdeka',
                'traffic_weekly_motor' => 1224972,
                'traffic_weekly_mobil' => 1048354,
                'traffic_weekly_bus' => 5973,
                'traffic_weekly_truk' => 17265,
                'traffic_monthly_motor' => 4761585,
                'traffic_monthly_mobil' => 4075087,
                'traffic_monthly_bus' => 23221,
                'traffic_monthly_truk' => 66962,
            ],
            [
                'code' => 'BB-05',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. S. PARMAN SIMP. JL. GLUGUR',
                'size' => '12 m x 6 m',
                'orientation' => 'Horizontal',
                'maps_link' => 'https://maps.app.goo.gl/6vTF14713aKUBA52A',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 14 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Menuju Plaza Medan Fair\nMenuju Deli Park Plaza ( Podomoro )\nDekat Showroom Mobil\nDekat Toko - Toko Elektronik\nDekat Kantor DPRD Sumut Kota Medan\n± 145m dari Sekolah Santo Thomas 1\nMenuju Kantor Walikota\nMenuju Lapangan Benteng\nMenuju Lapangan Merdeka',
                'traffic_weekly_motor' => 1310703,
                'traffic_weekly_mobil' => 1121738,
                'traffic_weekly_bus' => 6387,
                'traffic_weekly_truk' => 18427,
                'traffic_monthly_motor' => 5282259,
                'traffic_monthly_mobil' => 4520718,
                'traffic_monthly_bus' => 25748,
                'traffic_monthly_truk' => 74272,
            ],
            [
                'code' => 'BB-06',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. S. PARMAN SIMP. MOJOPAHIT',
                'size' => '10 m x 5 m',
                'orientation' => 'Horizontal',
                'maps_link' => 'https://maps.app.goo.gl/ioVGdVDNJuIDJp4r5',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 12 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Dekat Pusat Kota\n± 145m dari Sekolah Santo Thomas 1\n± 480m dari Cambridge City Square\nMenuju Plaza Medan Fair\nMenuju Deli Park Plaza ( Podomoro )\nMenuju Kantor Walikota\nMenuju Lapangan Benteng\nMenuju Lapangan Merdeka\nDekat Showroom Mobil\nDekat Toko - Toko Elektronik',
                'traffic_weekly_motor' => 1310453,
                'traffic_weekly_mobil' => 1121563,
                'traffic_weekly_bus' => 6379,
                'traffic_weekly_truk' => 18434,
                'traffic_monthly_motor' => 5282461,
                'traffic_monthly_mobil' => 4520721,
                'traffic_monthly_bus' => 25421,
                'traffic_monthly_truk' => 74254,
            ],
            [
                'code' => 'BB-07',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. S. PARMAN SIMP. MOJOPAHIT',
                'size' => '5 m x 10 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/tWJckDX1zYvqEcyE6',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 12 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => '± 60m dari Sekolah Santo Thomas 1\n± 290m dari Pasar Petisah Medan\n± 415m dari Cambridge City Square\nMenuju Plaza Medan Fair\nMenuju Deli Park Plaza ( Podomoro )\nMenuju Lapangan Merdeka\nDekat dengan Pertokoan',
                'traffic_weekly_motor' => 1310724,
                'traffic_weekly_mobil' => 1121746,
                'traffic_weekly_bus' => 6383,
                'traffic_weekly_truk' => 18425,
                'traffic_monthly_motor' => 5282265,
                'traffic_monthly_mobil' => 4520728,
                'traffic_monthly_bus' => 25745,
                'traffic_monthly_truk' => 74277,
            ],
            [
                'code' => 'BB-08',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. S. PARMAN SIMP. KEJAKSAAN',
                'size' => '6 m x 12 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/nFAuJ9NNEVPTGLfi6',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 18 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => '± 125m dari pusat oleh-oleh Jl. Mojopahit\n± 200m dari Mall Cambridge City Square\nMenuju Sekolah Santo Thomas 1\nDekat RS Mitra Medika Premiere\n± 50m dari KPU Kota Medan\nMenuju Plaza Medan Fair\nDekat Showroom Mobil',
                'traffic_weekly_motor' => 1410902,
                'traffic_weekly_mobil' => 1191734,
                'traffic_weekly_bus' => 6396,
                'traffic_weekly_truk' => 18447,
                'traffic_monthly_motor' => 5294009,
                'traffic_monthly_mobil' => 4588798,
                'traffic_monthly_bus' => 25771,
                'traffic_monthly_truk' => 74282,
            ],
            [
                'code' => 'BB-11',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. HM YAMIN',
                'size' => '6 m x 12 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/rk6zSE4vL9MV7itD9',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 14 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Simpang Rel Kereta Api\nDekat Lapangan Merdeka\nDekat Stasiun KA\nMenuju Deli Park Plaza\nMenuju Plaza Medan Fair\nMenuju Lapangan Benteng\nArea Kuliner',
                'traffic_weekly_motor' => 1184377,
                'traffic_weekly_mobil' => 1065480,
                'traffic_weekly_bus' => 5762,
                'traffic_weekly_truk' => 16524,
                'traffic_monthly_motor' => 5780792,
                'traffic_monthly_mobil' => 4959164,
                'traffic_monthly_bus' => 26463,
                'traffic_monthly_truk' => 76265,
            ],
            [
                'code' => 'BB-12',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. RINGROAD SIMP. ASOKA',
                'size' => '10 m x 5 m',
                'orientation' => 'Horizontal',
                'maps_link' => 'https://maps.app.goo.gl/xy2Tqe9xdgU277fm8',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 12 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Pusat Cafe & Resto Sekitar Focal Point & Ringroad City Walk\n± 30m dari Honda Arista Ringroad\nMenuju Ringroad City Walks\nMenuju Focal Point',
                'traffic_weekly_motor' => 1231341,
                'traffic_weekly_mobil' => 1218378,
                'traffic_weekly_bus' => 5998,
                'traffic_weekly_truk' => 17267,
                'traffic_monthly_motor' => 4780164,
                'traffic_monthly_mobil' => 4089292,
                'traffic_monthly_bus' => 23345,
                'traffic_monthly_truk' => 67051,
            ],
            [
                'code' => 'BL-19',
                'type' => 'Baliho',
                'name' => 'BALIHO JL. DR MANSYUR',
                'size' => '4 m x 6 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/sMX4qiDwTDnVnhbB9',
                'spesifikasi' => 'Baliho Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 4 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Pusat Cafe & Resto Sekitar USU\n± 130m dari SPBU\n± 320m dari Bank BNI USU\nDekat Kampus USU\nMenuju Perumahan Taman Setia Budi',
                'traffic_weekly_motor' => 1234751,
                'traffic_weekly_mobil' => 1618356,
                'traffic_weekly_bus' => 5195,
                'traffic_weekly_truk' => 17276,
                'traffic_monthly_motor' => 4779524,
                'traffic_monthly_mobil' => 4092462,
                'traffic_monthly_bus' => 23243,
                'traffic_monthly_truk' => 66820,
            ],
            [
                'code' => 'BB-20',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. CIREBON',
                'size' => '5 m x 10 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/5XFbWjiSoRoi5XQN9',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 12 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Pusat Kota\nPusat Pertokoan\n± 800m dari Mall Center Point\nMenuju Ramayana Teladan\nMenuju Yuki Simp. Raya\nMenuju Mesjid Raya',
                'traffic_weekly_motor' => 1290813,
                'traffic_weekly_mobil' => 1119838,
                'traffic_weekly_bus' => 6334,
                'traffic_weekly_truk' => 18412,
                'traffic_monthly_motor' => 5275812,
                'traffic_monthly_mobil' => 4512871,
                'traffic_monthly_bus' => 25721,
                'traffic_monthly_truk' => 74298,
            ],
            [
                'code' => 'BB-22',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. T. AMIR HAMZAH',
                'size' => '6 m x 12 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/WsFMvt9Mqh9d6V67',
                'spesifikasi' => 'Billboard Backlite - Premium Area\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => '± 630m dari Milenium ICT Center\n± 680m dari Griya Riatur Indah\nPusat dan Cafe Resto\nMenuju Restoran Lembur Kuring',
                'traffic_weekly_motor' => 763168,
                'traffic_weekly_mobil' => 653420,
                'traffic_weekly_bus' => 3725,
                'traffic_weekly_truk' => 10736,
                'traffic_monthly_motor' => 3155769,
                'traffic_monthly_mobil' => 2700802,
                'traffic_monthly_bus' => 15385,
                'traffic_monthly_truk' => 44379,
            ],
            [
                'code' => 'BB-23',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. KAPTEN MUSLIM SIMP. AMIR HAMZAH',
                'size' => '5 m x 10 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/XJpsSjtiW2B6yPS57',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 10 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Dekat Mall Plaza Millenium\nDekat Tempat Kuliner Amir Hamzah\nDekat Perumahan Mewah Amir Hamzah\nDekat Mandiri Supermarket\nMenuju Pasar Sei Kambing',
                'traffic_weekly_motor' => 763157,
                'traffic_weekly_mobil' => 653136,
                'traffic_weekly_bus' => 3720,
                'traffic_weekly_truk' => 10732,
                'traffic_monthly_motor' => 3155754,
                'traffic_monthly_mobil' => 2700790,
                'traffic_monthly_bus' => 15382,
                'traffic_monthly_truk' => 44372,
            ],
            [
                'code' => 'BB-24',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. YOS SUDARSO FLYOVER PULO BRAYAN',
                'size' => '6 m x 12 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/fvSDtVGP1nrLPCVc7',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 10 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Traffic Padat Lampu Merah\nDekat Pulo Brayan Flyover\nDekat Pasar Brayan\nPusat Pertokoan',
                'traffic_weekly_motor' => 1381519,
                'traffic_weekly_mobil' => 1182348,
                'traffic_weekly_bus' => 6736,
                'traffic_weekly_truk' => 19423,
                'traffic_monthly_motor' => 5420762,
                'traffic_monthly_mobil' => 4639254,
                'traffic_monthly_bus' => 26423,
                'traffic_monthly_truk' => 76220,
            ],
            [
                'code' => 'BB-25',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. YOS SUDARSO FLYOVER PULO BRAYAN',
                'size' => '6 m x 12 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/o1KdjWdfuoihJuFv5',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 10 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Traffic Padat Lampu Merah\nDekat Pulo Brayan Flyover\nDekat Pasar Brayan\nPusat Pertokoan',
                'traffic_weekly_motor' => 763168,
                'traffic_weekly_mobil' => 653420,
                'traffic_weekly_bus' => 3725,
                'traffic_weekly_truk' => 10736,
                'traffic_monthly_motor' => 3155769,
                'traffic_monthly_mobil' => 2700802,
                'traffic_monthly_bus' => 15385,
                'traffic_monthly_truk' => 44379,
            ],
            [
                'code' => 'BB-26',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. YOS SUDARSO SIMP. BILAL',
                'size' => '6 m x 12 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/ETh45nNQe1ywwzvf8',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 10 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Menuju Perumahan Komplek Cemara Asri\nDekat Perumahan Villa Glugur Mas\nDekat Showroom Yamaha Mptpr\nDekat STMIK Logika\nDekat SMAN 3 Medan\nDekat SMP Swasta Pertiwi\nDekat Perguruan STBA-PIA',
                'traffic_weekly_motor' => 1367687,
                'traffic_weekly_mobil' => 1173678,
                'traffic_weekly_bus' => 6698,
                'traffic_weekly_truk' => 19573,
                'traffic_monthly_motor' => 5434786,
                'traffic_monthly_mobil' => 4654678,
                'traffic_monthly_bus' => 26319,
                'traffic_monthly_truk' => 76412,
            ],
            [
                'code' => 'BB-27',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. YOS SUDARSO SIMP. JL. ADAM MALIK',
                'size' => '16 m x 8 m',
                'orientation' => 'Horizontal',
                'maps_link' => 'https://maps.app.goo.gl/cQtbvWup2gaMPeUTA',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nPemberhentian Lampu Merah ± 4 menit\nLampu Sorot LED 100 watt sebanyak 24 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Pusat Kota\nDekat pusat pertokoan\nSimpang Lampu Merah\nMenuju Pasar Brayan\nMenuju Sekolah Dharmawangsa\nMenuju Universitas Muhammadiyah Sumatera Utara ( UMSU )',
                'traffic_weekly_motor' => 1322512,
                'traffic_weekly_mobil' => 1162456,
                'traffic_weekly_bus' => 6891,
                'traffic_weekly_truk' => 19539,
                'traffic_monthly_motor' => 5561072,
                'traffic_monthly_mobil' => 4714127,
                'traffic_monthly_bus' => 27110,
                'traffic_monthly_truk' => 77183,
            ],
            [
                'code' => 'BB-29',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. YOS SUDARSO SIMP. JL. KARANTINA',
                'size' => '6 m x 12 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/EQSRD2LpxHX87PpL7',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 150 watt sebanyak 12 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Pusat Kota\nDekat pusat pertokoan\nSimpang Lampu Merah\nMenuju Pasar Brayan\nMenuju Sekolah Dharmawangsa\nMenuju Universitas Muhammadiyah Sumatera Utara ( UMSU )',
                'traffic_weekly_motor' => 1381519,
                'traffic_weekly_mobil' => 1182348,
                'traffic_weekly_bus' => 6736,
                'traffic_weekly_truk' => 19423,
                'traffic_monthly_motor' => 5420762,
                'traffic_monthly_mobil' => 4639254,
                'traffic_monthly_bus' => 26423,
                'traffic_monthly_truk' => 76220,
            ],
            [
                'code' => 'BB-30',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. GAHARU SIMP. JL. ADAM MALIK',
                'size' => '5 m x 10 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/91G6c4V37PC5tuFa7',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 12 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Dekat Kampus UMSU\nDekat Showroom Mobil\nDekat Toko - Toko Elektronik\nMenuju Sekolah Dharmawangsa',
                'traffic_weekly_motor' => 1174872,
                'traffic_weekly_mobil' => 1005490,
                'traffic_weekly_bus' => 5730,
                'traffic_weekly_truk' => 16519,
                'traffic_monthly_motor' => 4606551,
                'traffic_monthly_mobil' => 3942427,
                'traffic_monthly_bus' => 22454,
                'traffic_monthly_truk' => 64772,
            ],
            [
                'code' => 'BB-32',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. GATOT SUBROTO SIMP. PINANG BARIS',
                'size' => '6 m x 12 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/wXwfPREKn7iBanc4A',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 12 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Dekat Pajak Kampung Lalang\nJalan Protokol Menuju Ke Binjai\nDekat Mall Manhattan City\nDekat Terminal Bus Pinang Baris',
                'traffic_weekly_motor' => 1320603,
                'traffic_weekly_mobil' => 1132415,
                'traffic_weekly_bus' => 6391,
                'traffic_weekly_truk' => 18456,
                'traffic_monthly_motor' => 5450022,
                'traffic_monthly_mobil' => 4647314,
                'traffic_monthly_bus' => 26424,
                'traffic_monthly_truk' => 76257,
            ],
            [
                'code' => 'BB-33',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. KARYA',
                'size' => '5 m x 10 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/UUNHStHpVQ7y1DN4',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 10 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => '± 70m dari Bank Mandiri KCP Medan Karya\n± 165m dari Masjid Nurul Islam\n± 520m dari STBA-PIA\nMenuju BPJS Kesehatan\nDekat Warung Makan',
                'traffic_weekly_motor' => 1234261,
                'traffic_weekly_mobil' => 1068760,
                'traffic_weekly_bus' => 5931,
                'traffic_weekly_truk' => 17211,
                'traffic_monthly_motor' => 1254561,
                'traffic_monthly_mobil' => 1048560,
                'traffic_monthly_bus' => 5945,
                'traffic_monthly_truk' => 17231,
            ],
            [
                'code' => 'BB-34',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. SISINGAMANGARAJA',
                'size' => '20 m x 10 m',
                'orientation' => 'Horizontal',
                'maps_link' => 'https://maps.app.goo.gl/NR5RFmevsXyVDo1d6',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nView ± 2 KM dari Fly Over Amplas\nLampu Sorot LED 100 watt sebanyak 40 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Dekat Indogrosir Medan\nDekat Asuransi Sinarmas\nDekat Waspada News TV\nDekat Astragraphia member of Astra\nDekat Showroom Mobil',
                'traffic_weekly_motor' => 2763063,
                'traffic_weekly_mobil' => 2376636,
                'traffic_weekly_bus' => 13472,
                'traffic_weekly_truk' => 38846,
                'traffic_monthly_motor' => 10841525,
                'traffic_monthly_mobil' => 9278578,
                'traffic_monthly_bus' => 52848,
                'traffic_monthly_truk' => 182448,
            ],
            [
                'code' => 'BB-35',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. SISINGAMANGARAJA',
                'size' => '6 m x 12 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/AdqrBobumQQBqfSN8',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 150 watt sebanyak 12 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Dekat Indogrosir Medan\nDekat Asuransi Sinarmas\nDekat Waspada News TV\nDekat Astragraphia member of Astra\nDekat Showroom Mobil\nMenuju Terminal Amplas\nMenuju Tanjung Morawa',
                'traffic_weekly_motor' => 2763038,
                'traffic_weekly_mobil' => 2364696,
                'traffic_weekly_bus' => 13472,
                'traffic_weekly_truk' => 38846,
                'traffic_monthly_motor' => 10841524,
                'traffic_monthly_mobil' => 9278508,
                'traffic_monthly_bus' => 52846,
                'traffic_monthly_truk' => 152440,
            ],
            [
                'code' => 'BB-39',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. A.H NASUTION',
                'size' => '5 m x 10 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/aDfGaXT8yNHKkMoQ8',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 10 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Dekat KFC Underpass\nDekat Ruko Kuliner dan Perkantoran',
                'traffic_weekly_motor' => 1183193,
                'traffic_weekly_mobil' => 1129109,
                'traffic_weekly_bus' => 5800,
                'traffic_weekly_truk' => 16201,
                'traffic_monthly_motor' => 5783611,
                'traffic_monthly_mobil' => 4962761,
                'traffic_monthly_bus' => 26231,
                'traffic_monthly_truk' => 77129,
            ],
            [
                'code' => 'SM-40',
                'type' => 'Semi Billboard',
                'name' => 'SEMI BILLBOARD JL. CEMARA',
                'size' => '4 m x 8 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/QHWfCSwhyYe3Srn18',
                'spesifikasi' => 'Semi Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 5 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Seberang Pintu Utama Komplek Cemara Asri\nSeberang dari Living World Plaza Kawan Lama\nPusat Pertokoan\nPusat Tempat Kuliner',
                'traffic_weekly_motor' => 1381528,
                'traffic_weekly_mobil' => 1182356,
                'traffic_weekly_bus' => 6732,
                'traffic_weekly_truk' => 19429,
                'traffic_monthly_motor' => 5420782,
                'traffic_monthly_mobil' => 4639294,
                'traffic_monthly_bus' => 26427,
                'traffic_monthly_truk' => 76234,
            ],
            [
                'code' => 'SM-41',
                'type' => 'Semi Billboard',
                'name' => 'SEMI BILLBOARD JL. WILLIAM ISKANDAR DEPAN RENJIRO RAMEN',
                'size' => '4 m x 8 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/R6vR12PxbZGQCDmX6',
                'spesifikasi' => 'Semi Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 8 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Depan Renjiro Ramen\nBanyak Pusat Makanan\nPadat Kendaraan\nMenuju Komplek Cemara Asri',
                'traffic_weekly_motor' => 1399879,
                'traffic_weekly_mobil' => 1569938,
                'traffic_weekly_bus' => 67454,
                'traffic_weekly_truk' => 19482,
                'traffic_monthly_motor' => 5617799,
                'traffic_monthly_mobil' => 4468981,
                'traffic_monthly_bus' => 28761,
                'traffic_monthly_truk' => 72288,
            ],
            [
                'code' => 'SM-42',
                'type' => 'Semi Billboard',
                'name' => 'SEMI BILLBOARD JL. WILLIAM ISKANDAR DEPAN RENJIRO RAMEN',
                'size' => '4 m x 8 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/vYQSKbV4aHUEvg5EA',
                'spesifikasi' => 'Semi Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 8 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Depan Renjiro Ramen\nBanyak Pusat Makanan\nPadat Kendaraan\nMenuju UNIMED',
                'traffic_weekly_motor' => 1410230,
                'traffic_weekly_mobil' => 1579199,
                'traffic_weekly_bus' => 67498,
                'traffic_weekly_truk' => 19538,
                'traffic_monthly_motor' => 5618663,
                'traffic_monthly_mobil' => 4469566,
                'traffic_monthly_bus' => 28816,
                'traffic_monthly_truk' => 72328,
            ],
            [
                'code' => 'BL-43',
                'type' => 'Baliho',
                'name' => 'BALIHO JL. CEMARA SIMP. HAJI ANIF',
                'size' => '4 m x 6 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/fR3SHEJTLlgKTjXDA',
                'spesifikasi' => 'Baliho Frontlite - Premium Area\nTanpa Penerangan',
                'keterangan' => '± 180m dari Lapangan Sepak Bola PTPN 2\nDekat Taman Simpang BW Sampali\nDekat Medan Online Center',
                'traffic_weekly_motor' => 1381518,
                'traffic_weekly_mobil' => 1182326,
                'traffic_weekly_bus' => 6710,
                'traffic_weekly_truk' => 19423,
                'traffic_monthly_motor' => 5420772,
                'traffic_monthly_mobil' => 4639264,
                'traffic_monthly_bus' => 26417,
                'traffic_monthly_truk' => 76223,
            ],
            [
                'code' => 'BL-44',
                'type' => 'Baliho',
                'name' => 'BALIHO JL. CEMARA SIMP. HAJI ANIF',
                'size' => '4 m x 6 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/ya2cDk4d1Txzaqsy6',
                'spesifikasi' => 'Baliho Frontlite - Premium Area\nTanpa Penerangan',
                'keterangan' => '± 180m dari Lapangan Sepak Bola PTPN 2\nDekat Taman Simpang BW Sampali\nDekat Medan Online Center',
                'traffic_weekly_motor' => 1381518,
                'traffic_weekly_mobil' => 1182326,
                'traffic_weekly_bus' => 6710,
                'traffic_weekly_truk' => 19423,
                'traffic_monthly_motor' => 5420772,
                'traffic_monthly_mobil' => 4639264,
                'traffic_monthly_bus' => 26417,
                'traffic_monthly_truk' => 76223,
            ],
            [
                'code' => 'BL-45',
                'type' => 'Baliho',
                'name' => 'BALIHO JL. GATOT SUBROTO SEBERANG PANCA BUDI',
                'size' => '4 m x 6 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/tzGben2euRe7pzuj8',
                'spesifikasi' => 'Baliho Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 4 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Trafik Padat\n± 105m dari Samsung Service Center\n± 116m dari Perguruan Panca Budi\nMenuju Plaza Medan Fair',
                'traffic_weekly_motor' => 1845869,
                'traffic_weekly_mobil' => 1564480,
                'traffic_weekly_bus' => 6123,
                'traffic_weekly_truk' => 17401,
                'traffic_monthly_motor' => 5252234,
                'traffic_monthly_mobil' => 4510628,
                'traffic_monthly_bus' => 25736,
                'traffic_monthly_truk' => 73274,
            ],
            [
                'code' => 'BL-46',
                'type' => 'Baliho',
                'name' => 'BALIHO JL. GATOT SUBROTO SEBERANG PANCA BUDI',
                'size' => '4 m x 6 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/LsUidjtLJTMQmrtG9',
                'spesifikasi' => 'Baliho Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 4 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Trafik Padat\n± 105m dari Samsung Service Center\n± 116m dari Perguruan Panca Budi\nMenuju Pasar Sei Kambing',
                'traffic_weekly_motor' => 1845869,
                'traffic_weekly_mobil' => 1564480,
                'traffic_weekly_bus' => 6123,
                'traffic_weekly_truk' => 17401,
                'traffic_monthly_motor' => 5252234,
                'traffic_monthly_mobil' => 4510628,
                'traffic_monthly_bus' => 25736,
                'traffic_monthly_truk' => 73274,
            ],
            [
                'code' => 'SM-49',
                'type' => 'Semi Billboard',
                'name' => 'SEMI BILLBOARD JL. BESAR TEMBUNG SIMP. JODOH',
                'size' => '4 m x 8 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/9CAHr11cuhUEJG27',
                'spesifikasi' => 'Semi Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 4 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Menuju Pajak Gambir\nMenuju Irian Jaya Supermarket\nDekat Simpang Jodoh\nDekat Pertokoan, dan Cafe',
                'traffic_weekly_motor' => 1381599,
                'traffic_weekly_mobil' => 1182393,
                'traffic_weekly_bus' => 6740,
                'traffic_weekly_truk' => 19439,
                'traffic_monthly_motor' => 5420801,
                'traffic_monthly_mobil' => 4639309,
                'traffic_monthly_bus' => 26432,
                'traffic_monthly_truk' => 76243,
            ],
            [
                'code' => 'SM-50',
                'type' => 'Semi Billboard',
                'name' => 'SEMI BILLBOARD JL. BESAR TEMBUNG SIMP. JODOH',
                'size' => '4 m x 8 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/awn77c8bAAPeaCnV7',
                'spesifikasi' => 'Semi Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 4 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => '± 300m dari Pajak Gambir\n± 700m dari Irian Jaya\nDekat Simpang Jodoh\nDekat Pertokoan, dan Cafe',
                'traffic_weekly_motor' => 1381599,
                'traffic_weekly_mobil' => 1182393,
                'traffic_weekly_bus' => 6740,
                'traffic_weekly_truk' => 19439,
                'traffic_monthly_motor' => 5420801,
                'traffic_monthly_mobil' => 4639309,
                'traffic_monthly_bus' => 26432,
                'traffic_monthly_truk' => 76243,
            ],
            [
                'code' => 'BL-54',
                'type' => 'Baliho',
                'name' => 'BALIHO JL. SEI BATANG HARI',
                'size' => '6 m x 4 m',
                'orientation' => 'Horizontal',
                'maps_link' => 'https://maps.app.goo.gl/AQMQaqhvFjKvzbu76',
                'spesifikasi' => 'Baliho Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 3 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Trafik Padat\nDekat Pusat Pertokoan & Resto\n± 65m Dekat Rumah Sakit Bunda Thamrin',
                'traffic_weekly_motor' => 1234786,
                'traffic_weekly_mobil' => 1618414,
                'traffic_weekly_bus' => 5207,
                'traffic_weekly_truk' => 17281,
                'traffic_monthly_motor' => 4779992,
                'traffic_monthly_mobil' => 4092632,
                'traffic_monthly_bus' => 23248,
                'traffic_monthly_truk' => 66980,
            ],
            [
                'code' => 'BB-55',
                'type' => 'Billboard',
                'name' => 'BILLBOARD JL. KATAMSO SIMP. JL. JUANDA',
                'size' => '5 m x 10 m',
                'orientation' => 'Vertikal',
                'maps_link' => 'https://maps.app.goo.gl/zojPuZtzE8tRntG69',
                'spesifikasi' => 'Billboard Frontlite - Premium Area\nLampu Sorot LED 100 watt sebanyak 14 pcs\nPenerangan dari pukul 18.00 - 01.00',
                'keterangan' => 'Trafik Padat\nDekat Pusat Pertokoan & Resto\n± 150m Dekat Dengan Istana Maimun\n± 500m Dekat Dengan Masjid Raya Medan\n± 150m Dekat Dengan Perpustakaan Daerah\n± 200m Dekat Dengan AZKO - Informa',
                'traffic_weekly_motor' => 1234786,
                'traffic_weekly_mobil' => 1618414,
                'traffic_weekly_bus' => 5207,
                'traffic_weekly_truk' => 17281,
                'traffic_monthly_motor' => 4779992,
                'traffic_monthly_mobil' => 4092632,
                'traffic_monthly_bus' => 23248,
                'traffic_monthly_truk' => 66980,
            ],
        ];

        foreach ($billboards as $data) {
            $data['slug'] = Str::slug($data['name'] . '-' . $data['code']);
            Billboard::create($data);
        }
    }
}
